"""
    This is a setup.py script generated by py2applet
    
    Usage:
    python setup.py py2app
    """

from setuptools import setup
#import py2exe

APP = ['BlueMoney.py']
RESOURCES = ['data', 'data/resources']
DATA_FILES = ['main.py', 'update.py', 'notify.py', 'error.py', 'repair.py', 'database.py', 'firstrun.py']
OPTIONS = {     'argv_emulation': True,
                'includes': ['PySide.QtCore', 'PySide.QtGui', 'PySide.QtWebKit', 'applescript'],
                'resources': RESOURCES,
                'iconfile':'data/resources/icon.icns',
                'plist':dict(CFBundleIconFile='icon')}

setup(
      app=APP,
      data_files=DATA_FILES,
      options={'py2app': OPTIONS},
      setup_requires=['py2app'],
)